---
title: "R Notebook"
output: html_notebook
---

```{r}
library(haven)
Data <- read.csv("/media/empro/5C02C2EB02C2C8EA/Ubuntu/Fendler/ovaryAnalysis/processed.csv", header = TRUE)
#View(Data)
```
```{r}
Labels <- Data[c(1)]
Data <- Data[-c(1)]
```

zbadamy macierz korelacji 
```{r}
corMatrix <- cor(Data, method = 'spearman')
```

```{r}
#heatm <- heatmap(corMatrix)
heatm <- heatmap(corMatrix, Rowv = NA, Colv = NA)
```
Mediany
```{r}
library(data.table)
View(Labels)
```
Sprawdz dystrybucje
```{r}
library(ggplot2)

for(colmn in Data)
{
  hist(colmn)
}
```

```{r}
toM <- subset(Data, Labels[c(1)] == 'can')
#View(toM)
#toM <- setDT(Data, key=Labels)['can']
```
policz mediane
```{r}
names <- c()
meds <- c()
ps <- c()
for(i in 1:ncol(toM))
{
  med = median(toM[, i])
  #print(median(as.numeric(as.vector(toM[c(i)]))) )
  name = colnames(toM)[i]
  p = wilcox.test(Data[, i] ~ Labels[, 1])$p.value
  
  #cat("Nazwa: ", name, "  mediana: ", med, "  p: ", p, "\n")
  
  names <- c(names, name)
  meds <- c(meds, med)
  ps <- c(ps, p)
}

```
```{r}
#meds <- log2(meds)
volData = data.frame(names, meds, ps)
#View(head(volData, n=10) )

volData <- volData[order(volData$ps),]
View(head(volData, n=10) )
```

Beniamini-Hochberg Procedure - NOPE
FDR
```{r}
bh = p.adjust(volData$ps, method = 'fdr')

#View(head(bh, n=10))

volData <- data.frame(volData, bh)

View(head(volData, n=10))
```

Rysujemy piękny volcanoPlot
```{r}
library(dplyr)
library(ggplot2)
```

```{r}
View(volData)
```

```{r}
drawRes = mutate(volData, sig=ifelse(volData$bh < 0.05, 'FDR<0.05', 'Not Sig'))

volPlo = ggplot(drawRes, aes(meds, -log10(ps))) + geom_point(aes(col=sig)) + scale_color_manual(values = c('red', 'black'))

#0volPlo <- volPlo + geom_text(data=filter(drawRes, bh<0.05), aes(label=names))

volPlo <- volPlo + scale_x_continuous(limits = c(-2, 2))

volPlo
```

move labels
```{r}
library(ggrepel)

volPlo <- volPlo + geom_text_repel(data=filter(drawRes, bh < 0.05), aes(label=names))
volPlo
```



Machine Learning